import Foundation

/// Lightweight localization helper for a SwiftPM package (no `.xcstrings` bundle).
/// `AppSettings` keeps `currentLanguage` in sync so both SwiftUI views and
/// services (notifications, orchestrator errors) resolve the same language.
enum L10n {
    static var currentLanguage: AppLanguage = .zh

    static func string(_ key: String, language: AppLanguage? = nil) -> String {
        let lang = language ?? currentLanguage
        let table = lang == .en ? enStrings : zhStrings
        return table[key] ?? key
    }

    static func string(_ key: String, language: AppLanguage? = nil, _ args: CVarArg...) -> String {
        let format = string(key, language: language)
        return String(format: format, locale: Locale(identifier: language?.bcp47 ?? currentLanguage.bcp47), arguments: args)
    }

    // MARK: - Chinese strings

    private static let zhStrings: [String: String] = [
        // Units
        "unit.times": "次",
        "app.alert.noKeyTitle": "未配置 API Key",
        "app.alert.noKeyBody": "AI 总结功能需要配置 API Key 才能使用。\n是否前往设置进行配置？",
        "app.alert.goToSettings": "前往设置",
        "app.alert.later": "稍后再说",
        "source.weibo": "微博热搜",
        "source.bilibili": "B站热搜",
        "bottom.overview": "总览",
        "bottom.openDashboard": "打开Dashboard",
        "bottom.openSettings": "打开设置",
        "bottom.refresh": "刷新",
        "bottom.refreshing": "刷新中...",

        // General
        "settings.general": "通用设置",
        "settings.general.subtitle": "刷新、外观与诊断",
        "settings.rss": "RSS 新闻源",
        "settings.rss.subtitle": "订阅、排序与展示方式",
        "settings.ai": "AI 编辑部",
        "settings.ai.subtitle": "提供商、模型与用量控制",
        "settings.about": "关于 NewsBar",
        "settings.about.subtitle": "版本、数据来源与隐私",
        "settings.notifications": "通知中心",
        "settings.notifications.subtitle": "权限、频率与每日摘要",
        "settings.tab.general": "通用",
        "settings.tab.rss": "RSS",
        "settings.tab.ai": "AI",
        "settings.tab.notifications": "通知",
        "settings.tab.about": "关于",
        "settings.tab.refresh": "刷新",
        "settings.tab.reminder": "提醒",
        "settings.tab.developer": "开发者",
        "settings.refresh": "刷新与诊断",
        "settings.refresh.subtitle": "智能刷新、状态与诊断日志",
        "settings.reminder": "提醒",
        "settings.reminder.subtitle": "定时推送、爆款与关键词监控",
        "settings.developer": "开发者",
        "settings.developer.subtitle": "测试、模型展开与调试",
        "settings.developer.update": "更新测试",
        "settings.developer.ai": "AI 调试",
        "settings.badge": "设置",
        "settings.quit": "退出 NewsBar",

        // Language
        "settings.language": "语言",
        "settings.language.footer": "切换界面语言。选择 English 后，可开启 RSS 标题翻译，AI 总结将以英文输出。",
        "settings.rssTranslation": "RSS 标题翻译",
        "settings.rssTranslation.footer": "开启后，RSS 标题将自动翻译为所选语言（使用免费 MyMemory 翻译服务）。微博与 B 站热搜保持原文。",

        // General - refresh
        "general.refresh": "刷新设置",
        "general.autoRefresh": "智能定时刷新",
        "general.autoRefresh.footer": "开启后，热搜在界面可见时约每 5 分钟、后台约每 30 分钟检查；RSS 根据更新活跃度在 30 分钟至 3 小时之间自适应。低电量与休眠状态会自动降频。",
        "general.status": "刷新状态",
        "general.todayRefreshCount": "今日刷新次数",
        "general.todayAICount": "今日 AI 调用",
        "general.estimatedAICost": "预估 AI 花费",
        "general.lastRefresh": "最后刷新",
        "general.status.footer": "含启动、定时和手动刷新；AI 花费仅估算 AI 总结请求，不包含微博、B站或 RSS。",
        "general.launch": "启动",
        "general.launchAtLogin": "开机自启",
        "general.theme": "主题设置",
        "general.retroTheme": "启用复古报刊编辑风",
        "general.theme.paper": "米白",
        "general.theme.brick": "砖红",
        "general.theme.ink": "墨黑",
        "general.themeSwatchAccessibility": "主题色 (%@)",
        "general.appearance": "明暗外观",
        "general.appearance.system": "跟随系统",
        "general.appearance.light": "浅色",
        "general.appearance.dark": "深色",
        "general.theme.footer.retro": "复古报刊主题固定使用米白纸张基底；关闭后恢复现代主题及明暗外观选择。",
        "general.theme.footer.modern": "现代主题支持跟随系统、浅色或深色；复古报刊主题使用 1960 年代编辑设计语言。",
        "general.diagnostics": "诊断",
        "general.diagnostics.footer": "记录最近 10 次刷新行为，仅保留诊断信息（不含 Key、密码等敏感数据）。",
        "general.refreshLog": "刷新日志",
        "general.noLogs": "暂无刷新记录",
        "general.copyLogs": "复制最近 10 次日志",
        "general.copied": "已复制",
        "general.clearLogs": "清空日志",
        "general.developer": "开发者选项",
        "general.forceLatest": "忽略版本号，强制下载最新版",
        "general.showAllModels": "显示全部 AI 模型",
        "general.developer.footer": "「忽略版本号」仅用于测试更新功能，开启后「检查更新」直接获取最新 release 版本。\n「显示全部 AI 模型」开启后，提供商模型列表不再折叠：有 DeepSeek 模型的供应商也会显示其全部官方模型（如 Ollama Cloud、MiniMax 等），默认仅显示 DeepSeek 系模型。",
        "general.log.trigger.startup": "启动",
        "general.log.trigger.timer1h": "定时",
        "general.log.trigger.scheduled": "智能调度",
        "general.log.trigger.wake": "唤醒",
        "general.log.trigger.manual": "手动",
        "general.log.trigger.popoverOpen": "弹窗",
        "general.log.trigger.burst": "爆款调研",

        // AI
        "ai.enable": "启用 AI 总结",
        "ai.feature": "功能开关",
        "ai.provider": "提供商",
        "ai.addCustomProvider": "添加自定义提供商",
        "ai.editProvider": "编辑",
        "ai.delete": "删除",
        "ai.provider.footer.custom": "当前为自定义提供商，可在上方编辑或删除。",
        "ai.apiKey": "API Key",
        "ai.save": "保存",
        "ai.saving": "保存中...",
        "ai.test": "测试连接",
        "ai.testing": "测试中...",
        "ai.apiKey.footer": "API Key 使用 AES-256-GCM 加密存储，绑定本机硬件。获取 Key: %@",
        "ai.1password": "1Password 集成",
        "ai.loadFrom1Password": "从 1Password 加载",
        "ai.loading": "加载中...",
        "ai.1password.footer": "格式: op://Vault/Item/Field。安装 op CLI (brew install 1password-cli) 并开启桌面集成后可使用。密钥加载后缓存 30 天。",
        "ai.model": "模型",
        "ai.modelSettings": "模型设置",
        "ai.model.footer": "默认折叠为 DeepSeek 系模型；可在「通用 → 开发者选项」开启「显示全部 AI 模型」查看供应商全部模型。",
        "ai.disableThinking": "关闭 DeepSeek 思考模式（更快输出）",
        "ai.disableThinking.footer": "DeepSeek V4 默认开启思考模式，思考过程会占用输出额度并拖慢速度。关闭后可大幅提速并避免摘要被截断；但会略微降低复杂归纳的精度。",
        "ai.summaryLength": "共享摘要长度",
        "ai.summaryLength.footer": "Popup 和 Dashboard 共用一次生成结果；Popup 每类最多显示 2 条，Dashboard 显示完整简报。",
        "ai.pricing": "费用说明",
        "ai.usage": "用量",
        "ai.usage.today": "今日已用（总计）",
        "ai.usage.shared": "同一份摘要同时服务 Popup 与 Dashboard，不重复计费。",
        "ai.usage.reset": "次日重置",
        "ai.limit": "限额",
        "ai.dailyCap": "每日请求上限",
        "ai.capTimes": "%ld 次",
        "ai.limit.footer": "共享摘要达到上限后当日不再发起 AI 请求，次日自动重置。",
        "ai.privacy": "隐私说明",
        "ai.privacy.body": "AI 总结功能会将当前新闻标题发送至您选择的 AI 提供商进行处理。我们不会记录您的原始标题内容或提示词。API Key 使用 AES-256-GCM 加密存储，绑定本机硬件。",
        "ai.deleteCustom.title": "删除自定义提供商？",
        "ai.deleteCustom.message": "将从列表中移除“%@”及其 API Key。此操作不可恢复。",
        "ai.deleteCustom.confirm": "删除 %@",
        "ai.cancel": "取消",
        "ai.saved": "已保存",
        "ai.saveFailed": "保存失败，请重试",
        "ai.test.success": "连接成功",
        "ai.test.empty": "返回为空",
        "ai.test.noKey": "请先输入或保存 API Key",
        "ai.test.emptyKey": "API Key 不能为空",
        "ai.test.invalidKey": "API Key 无效 (401)",
        "ai.test.requestFailed": "请求失败，请检查网络或模型名",
        "ai.test.invalidURL": "内部错误：URL 无效",
        "ai.test.parseFailed": "响应解析失败，模型可能不可用",
        "ai.test.parseFailedDetail": "响应解析失败：%@",
        "ai.test.unknown": "未知错误",
        "ai.test.timeout": "连接超时（30s），请检查网络或代理",
        "ai.test.noNetwork": "无网络连接",
        "ai.test.cannotFindHost": "无法解析服务器：%@",
        "ai.test.networkLost": "网络连接中断",
        "ai.test.networkError": "网络错误：%@",
        "ai.test.badResponse": "服务器返回格式异常，请检查模型是否可用",
        "ai.test.failed": "连接失败：%@",
        "ai.1p.invalidRef": "格式错误：应以 op:// 开头，格式为 op://Vault/Item/Field",
        "ai.1p.notInstalled": "1Password CLI 未安装，请运行: brew install 1password-cli",
        "ai.1p.timeout": "超时：请先解锁 1Password 桌面应用",
        "ai.1p.readFailed": "读取失败：请检查引用格式和权限",
        "ai.1p.success": "加载成功，已保存",
        "ai.1p.saveFailed": "保存失败，请重试",
        "ai.1p.unknown": "未知错误",
        "ai.custom.title.add": "添加自定义提供商",
        "ai.custom.title.edit": "编辑提供商",
        "ai.custom.name": "昵称",
        "ai.custom.endpoint": "端点 URL",
        "ai.custom.defaultModel": "默认模型",
        "ai.custom.models": "模型列表（每行一个 model id）",
        "ai.custom.anthropic": "Anthropic 兼容格式",
        "ai.custom.authHeaderName": "认证头名称（默认 x-api-key）",
        "ai.custom.authPrefix": "认证前缀（默认空）",
        "ai.custom.apiVersion": "API 版本（默认 2023-06-01）",
        "ai.custom.authHeaderNameOpenAI": "认证头名称（默认 Authorization）",
        "ai.custom.authPrefixOpenAI": "认证前缀（默认 Bearer ）",
        "ai.custom.pricing": "计费说明（可选）",
        "ai.custom.needModel": "请至少填写一个模型",
        "ai.custom.invalidURL": "端点 URL 无效",
        "ai.custom.save": "保存",
        "ai.custom.cancel": "取消",

        // RSS
        "rss.displayCount": "展示数量",
        "rss.unifiedCount": "统一展示数量",
        "rss.textFlow": "文本流",
        "rss.imageFlow": "图片流",
        "rss.displayCount.footer.unified": "开启后，所有 RSS 源共用同一组文本/图片展示数量。",
        "rss.displayCount.footer.perSource": "关闭后，可在每个 RSS 源行中按当前展示模式单独设置数量；右键可重置为全局默认值。",
        "rss.subscribed": "已订阅 RSS 源",
        "rss.hideRecommendations": "隐藏推荐",
        "rss.showRecommendations": "推荐列表",
        "rss.subscribed.footer": "拖拽已订阅源可调整展示顺序；文本流/图片流设置会保留。",
        "rss.unsubscribed": "未订阅 RSS 源",
        "rss.recommendationValidation": "推荐验证",
        "rss.recommendationValidation.footer": "只测试未添加推荐源；测试不会修改订阅、排序或通知。",
        "rss.addSource": "添加 RSS 源",
        "rss.empty": "暂无 RSS 源，点击下方推荐列表或手动添加",
        "rss.emptySubscribed": "暂无已订阅 RSS 源，可在未订阅列表中勾选",
        "rss.delete.title": "删除 RSS 源？",
        "rss.delete.message": "将从订阅和未订阅列表中移除“%@”。此操作不会删除本地缓存文件，但需要重新添加才能恢复。",
        "rss.delete.confirm": "删除 %@",
        "rss.delete.cancel": "取消",
        "rss.textMode": "文本流",
        "rss.imageMode": "图片流",
        "rss.switchToText": "%@ 切换为文本流",
        "rss.switchToImage": "%@ 切换为图片流",
        "rss.imageUnavailable": "%@ 图片流不可用",
        "rss.noImages": "此源暂无图片",
        "rss.moveUp": "将 %@ 上移",
        "rss.moveDown": "将 %@ 下移",
        "rss.up": "上移",
        "rss.down": "下移",
        "rss.subscribe": "订阅 %@",
        "rss.unsubscribe": "取消订阅 %@",
        "rss.subscribe.short": "订阅",
        "rss.unsubscribe.short": "取消订阅",
        "rss.resetToGlobal": "重置为全局默认",
        "rss.countAccessibility": "%@ %@展示数量",
        "rss.countHint": "按住或右键可重置为全局默认展示数量。",
        "rss.resetCount": "重置%@展示数量",
        "rss.delete": "删除 %@",
        "rss.delete.short": "删除",
        "rss.deleteHint": "需要确认后才会移除此 RSS 源。",
        "rss.dragReorder": "拖拽排序 %@",
        "rss.dragReorderShort": "拖拽排序",
        "rss.dragHint": "按住并拖动以调整已订阅 RSS 源顺序",
        "rss.add": "添加",
        "rss.addNamed": "添加 %@",
        "rss.addHint": "添加前会先通过安全策略验证。",
        "rss.alreadyExists": "该推荐已存在，无需重复添加",
        "rss.blocked": "推荐源已拦截：%@",
        "rss.warning": "推荐源存在安全警告：%@",
        "rss.testAll": "测试全部未添加",
        "rss.retryFailed": "重试失败/已取消",
        "rss.continueTesting": "继续测试未完成",
        "rss.testHint.retry": "仅重新验证失败、已取消或尚未完成的推荐，成功项保持不变。",
        "rss.testHint.continue": "继续验证上次未完成的推荐，已通过项不会重复测试。",
        "rss.testHint.all": "按顺序验证所有未添加推荐，测试过程不会更改订阅列表。",
        "rss.cancel": "取消",
        "rss.cancelValidation": "取消推荐验证",
        "rss.cancelValidationHint": "停止后续尚未开始的推荐；当前正在处理的源会在可取消点结束。",
        "rss.progress": "进度 %ld/%ld",
        "rss.current": "当前：%@",
        "rss.waitingNext": "等待下一项",
        "rss.testing": "测试中",
        "rss.noTestable": "暂无可测试的推荐",
        "rss.testOnlyUnadded": "仅测试未添加推荐",
        "rss.added": "已添加",
        "rss.addedHint": "推荐源已加入订阅列表。",
        "rss.testingBadge": "测试中",
        "rss.testingBadgeHint": "正在串行验证此推荐。",
        "rss.pending": "待测",
        "rss.pendingHint": "尚未开始验证。",
        "rss.blockedBadge": "已拦截",
        "rss.blockedBadgeHint": "安全策略拦截：%@",
        "rss.invalidURL": "URL 无效",
        "rss.invalidURLHint": "地址格式无效。",
        "rss.cancelled": "已取消",
        "rss.cancelledHint": "验证已停止，后续推荐未继续。",
        "rss.cancelledWithBody": "已取消：%@；%ld 项停止",
        "rss.networkFailed": "网络失败",
        "rss.networkFailedHint": "%@",
        "rss.notRSS": "非 RSS",
        "rss.notRSSHint": "返回内容不是 RSS 或 Atom。",
        "rss.passed": "通过",
        "rss.passedHint": "验证通过，约 %ld 项内容。",
        "rss.noRetryable": "暂无可重试的推荐",
        "rss.retrying": "重试中 %ld 项",
        "rss.testingCount": "测试中 %ld 项",
        "rss.cancelledStop": "已取消，后续推荐已停止",
        "rss.testingProgress": "测试中 %ld/%ld",
        "rss.retryDone": "重试完成",
        "rss.testDone": "测试完成",
        "rss.noResult": "无结果",
        "rss.cancelledResult": "已取消：%ld 项停止",
        "rss.passedCount": "%ld 通过",
        "rss.failedCount": "%ld 失败",
        "rss.sourceName": "源名称",
        "rss.url": "RSS URL",
        "rss.addAndValidate": "添加并验证",
        "rss.waterfall.imageMode": "图文",
        "rss.waterfall.textMode": "纯文本",
        "rss.waterfall.imagePlaceholder": "RSS 图像",
        "rss.readOriginal": "阅读原文",
        "rss.waterfall.accessibility": "%@，%@",
        "rss.waterfall.accessibilityDash": "%@ - %@",
        "rss.needURL": "请输入 RSS URL",
        "rss.notValidFeed": "该地址不是有效的 RSS/Atom Feed",
        "rss.cannotConnect": "无法连接到该地址",
        "rss.security.invalidURL": "URL 或协议无效",
        "rss.security.blockedHost": "已拦截主机：%@",
        "rss.security.privateIP": "私有网段：%@",
        "rss.network.timedOut": "请求超时",
        "rss.network.cannotConnect": "无法连接服务器",
        "rss.network.noInternet": "没有网络连接",
        "rss.network.serverNotFound": "未找到服务器",
        "rss.network.invalidResponse": "服务器响应无效",
        "rss.network.serverError": "服务器返回错误",
        "rss.network.parseFailed": "订阅内容解析失败",
        "rss.network.unexpected": "发生未知错误",
        "rss.network.generic": "网络错误",

        // Notifications
        "notif.hourly": "每小时推送",
        "notif.daily": "每日推送",
        "notif.pushCount": "推送条数",
        "notif.dailyTime": "每日推送时间",
        "notif.permission": "通知权限",
        "notif.permission.granted": "已授权",
        "notif.permission.denied": "已拒绝",
        "notif.permission.notDetermined": "未请求",
        "notif.requestPermission": "请求通知权限",
        "notif.openSettings": "打开系统设置",
        "notif.hourlyTitle": "NewsBar 更新",
        "notif.dailyTitle": "NewsBar 每日摘要",
        "notif.clickToView": "点击查看今日新闻",
        "notif.grantedTitle": "通知权限已开启",
        "notif.notGrantedTitle": "通知权限未开启",
        "notif.openSystemSettings": "前往系统设置",
        "notif.permissionStatus": "权限状态",
        "notif.hourlyPushNews": "每小时推送最新新闻",
        "notif.scheduled": "定时推送",
        "notif.dailyDigest": "每日摘要推送",
        "notif.pushTime": "推送时间",
        "notif.dailyPush": "每日推送",
        "notif.pushCountLabel": "每次推送条数: %ld",
        "notif.pushQuantity": "推送数量",
        "notif.pushCount.footer": "每小时推送在每次自动刷新后发送最新内容；每日推送在指定时间发送，内容为最近一次刷新结果。",
        "notif.burstPush": "爆款实时推送",
        "notif.burst": "爆款推送",
        "notif.burst.footer": "遇到微博“爆”标签时，立即推送单条新闻并调用 AI 调研（来龙去脉与时间线）。",
        "notif.webSearch": "联网搜索调研",
        "notif.webSearchHeader": "联网搜索",
        "notif.webSearch.footer": "开启后爆款调研使用 Firecrawl 联网搜索（keyless 免费层）；关闭则降级为纯 AI 生成。留空 API Key 即使用免费额度。",
        "notif.firecrawlKey": "Firecrawl API Key（可选）",
        "notif.keywordTracking": "关键词监控",
        "notif.keywordTracking.footer": "扫描微博、B站热搜与已启用 RSS 的标题，命中任一关键词即推送单条通知并调用 AI 调研（来龙去脉与时间线）。",
        "notif.keywordPrompt": "要关注的关键词",
        "notif.keywordAdd": "添加关键词",
        "notif.keywordEmpty": "暂无关键词，请输入后回车添加。",
        "notif.keywordRemove": "移除 %@",
        "notif.keywordTitle": "关键词命中",

        // Burst (爆) topic
        "notif.burstTitle": "微博爆款",
        "burst.badge": "爆款热闻",
        "burst.subtitle": "AI 调研 · 来龙去脉与时间线",
        "burst.loading": "AI 正在调研该事件...",
        "burst.failed": "调研失败，请稍后重试",
        "burst.retry": "重新调研",
        "burst.summary": "快速总结",
        "burst.summary.subtitle": "一句话了解事件",
        "burst.overview": "来龙去脉",
        "burst.overview.subtitle": "事件的完整脉络",
        "burst.timeline": "时间线",
        "burst.timeline.subtitle": "事件发展的时间节点",
        "burst.sources": "信息源",
        "burst.sources.subtitle": "本次调研引用的来源",
        "burst.noTimeline": "当前素材不足以支撑时间线，仅展示概要。",
        "burst.noSummary": "暂无摘要",
        "burst.searchFailed": "联网搜索失败，已降级为纯 AI 生成（详情见刷新日志）。",
        "burst.testMode": "爆款推送测试模式",
        "burst.testMode.footer": "「联网搜索调研」决定模拟推送是否调用 Firecrawl 联网搜索（独立于通知页的实时搜索开关）。模拟推送会先弹出详情窗再后台调研。",
        "burst.testWebSearch": "联网搜索调研",
        "burst.testPush": "模拟爆款推送",
        "burst.testTopic.placeholder": "输入要测试的热搜标题",
        "burst.testTopic.fillTop": "填入当前热搜第一",

        // About
        "about.version": "版本",
        "about.license": "许可证",
        "about.source": "数据来源",
        "about.privacy": "隐私",
        "about.checkUpdate": "检查更新",
        "about.versionText": "版本 %@ (%@)",
        "about.weibo": "微博热搜",
        "about.bilibili": "B站热搜",
        "about.rss": "RSS 源",
        "about.rssCustom": "用户自定义",
        "about.dataSources": "数据来源",
        "about.aiModels": "支持多种 AI API，可自由选择模型",
        "about.aiProviders": "AI 提供商",
        "about.clearCache": "清除所有缓存",
        "about.dataManagement": "数据管理",
        "about.privacy1": "NewsBar 不会收集任何个人信息。",
        "about.privacy2": "API Key 仅以机器绑定的加密文件保存在本地。",
        "about.privacy3": "缓存数据仅保存新闻标题，不包含用户数据。",
        "about.privacy4": "所有网络请求通过 HTTPS 加密传输。",
        "about.privacyTitle": "隐私说明",
        "about.keywords": "关键词: macOS 菜单栏·新闻聚合·AI 摘要·微博热搜·B站热搜·RSS 阅读器",
        "about.licenseTitle": "许可与信息",
        "about.clearCache.title": "清除所有缓存？",
        "about.cancel": "取消",
        "about.clearCache.message": "将清除本地新闻缓存。下次打开或刷新时需要重新加载内容。",

        // Popover
        "popover.trending": "即时热榜",
        "popover.trending.subtitle": "微博与 B 站正在发生的头条",
        "popover.weibo": "微博热搜",
        "popover.bilibili": "B站热搜",
        "popover.rss.subtitle": "订阅源 · 编辑精选",
        "popover.collapse": "%@ · 收起",
        "popover.allFailed": "所有新闻源更新失败，请稍后重试",
        "popover.quit.title": "退出 NewsBar？",
        "popover.quit.message": "NewsBar 将停止刷新新闻和发送通知。",
        "popover.quit.confirm": "退出 NewsBar",
        "popover.quit.cancel": "取消",
        "popover.quit.help": "退出 NewsBar",
        "popover.issueDate": "上海版",
        "popover.issueNumber": "NO. %@",

        // News section
        "news.clickToOpen": "点击打开浏览器",
        "news.loading": "加载中",
        "news.loadingDots": "加载中...",
        "news.loadFailed": "加载失败",
        "news.noData": "暂无数据",
        "news.staleCache": "更新失败，显示缓存",
        "news.expand": "展开 %ld 条",
        "news.collapse": "收起",
        "news.collapseCount": "收起 %ld 条",
        "news.count": "%ld 条",
        "news.openInBrowser": "在浏览器中打开",
        "news.rank": "第%ld位，%@，%@",
        "news.rankBadge": "排名第%ld",
        "news.rankAccessibility": "第%ld位，%@，%@",

        // AI summary card
        "aiCard.title": "AI 总结",
        "aiCard.subtitle": "趋势概览 / 每日精选 · 有引用显示来源徽章，点击打开原文",
        "aiCard.expandHint": "展开AI总结",
        "aiCard.collapseHint": "收起AI总结",
        "aiCard.noKey": "未配置",
        "aiCard.fetching": "获取中",
        "aiCard.summarizing": "思考中",
        "aiCard.failed": "失败",
        "aiCard.done": "已完成",
        "aiCard.truncated": "不完整",
        "aiCard.idle": "等待",
        "aiCard.noKeyTitle": "API Key 未配置",
        "aiCard.noKeyBody": "需要配置 AI API Key 才能使用 AI 总结功能",
        "aiCard.configureKey": "配置 Key",
        "aiCard.fetchingData": "获取新闻数据...",
        "aiCard.thinking": "AI 思考中...",
        "aiCard.maybeIncomplete": "摘要可能不完整",
        "aiCard.trendOverview": "趋势概览",
        "aiCard.dailyEssentials": "每日精选",
        "aiCard.regenerating": "生成中...",
        "aiCard.cooldown": "冷却中 %ld秒",
        "aiCard.regenerate": "重新生成",
        "aiCard.regenerateHint": "重新生成 Popup 与 Dashboard 共用的 AI 总结。",
        "aiCard.cooldownHint": "请等待冷却结束后再重新生成。",
        "aiCard.openSource": "打开 %@ 原文",
        "aiCard.openInBrowser": "在浏览器中打开",
        "aiCard.readonly": "这是只读摘要内容。",
        "aiCard.sourceHint": "可使用来源按钮打开原文。",
        "aiCard.noSource": "无可用来源",

        // Dashboard
        "dash.briefing": "AI Briefing",
        "dash.briefing.subtitle": "趋势概览 / 每日精选 · 有引用显示来源徽章，点击打开原文",
        "dash.refresh": "独立刷新 AI 简报",
        "dash.trendOverview": "趋势概览 %ld",
        "dash.dailyEssentials": "每日精选 %ld",
        "dash.trendCardSubtitle": "原生热点卡片 · 点击打开浏览器",
        "dash.collapseCard": "收起 %@",
        "dash.expandCard": "展开更多 %@",
        "dash.expandAll": "展开全部",
        "dash.noTrendData": "暂无趋势数据",
        "dash.waterfallSubtitle": "自适应瀑布流 · 点击在浏览器中打开",
        "dash.noRSSContent": "暂无 RSS 内容",
        "dash.rssLoading": "RSS 源加载中…",
        "dash.rssLoadingCache": "RSS 源加载中，当前显示缓存内容",
        "dash.trendRankAccessibility": "%@ 第%ld位，%@",
        "dash.source.idle": "空闲",
        "dash.source.loading": "加载中",
        "dash.source.loaded": "已加载",
        "dash.source.failed": "失败",
        "dash.rssBatchRefreshing": "RSS 批量刷新中",
        "dash.legacyNote": "当前摘要使用兼容解析：仍保留引用快照，且可继续切换查看两类内容。",
        "dash.fallbackNote": "当前没有引用快照，源链接需要重新刷新后才能恢复。",
        "dash.fallbackTitle": "摘要内容可用，但尚未解析为双分类结构。",
        "dash.emptyCategory": "当前分类暂无内容",
        "dash.noBriefing": "暂无可展示的 AI 简报",
        "dash.openSettings": "重新打开设置",
        "dash.state.idle": "等待 AI 简报",
        "dash.state.noKey": "未配置 API Key",
        "dash.state.fetching": "正在抓取新闻",
        "dash.state.summarizing": "AI 正在生成简报",
        "dash.state.done": "AI 简报已完成",
        "dash.state.truncated": "AI 简报已完成但内容被截断",
        "dash.state.error": "AI 简报生成失败",
        "dash.compatFormat": "兼容格式",
        "dash.configureKey": "配置 AI Key",
        "dash.searchPlaceholder": "搜索微博、B站热搜与 RSS 标题…",
        "dash.searchClear": "清除搜索",
        "dash.filter.all": "全部",
        "dash.filter.rss": "RSS",
        "dash.filterCount": "%ld 条匹配",

        // Errors
        "error.invalidURL": "无效的 URL",
        "error.requestFailed": "网络请求失败",
        "error.parseFailed": "数据解析失败",
        "error.parseFailedDetail": "XML 解析失败: %@",
        "error.apiKeyInvalid": "API Key 无效",
        "error.rateLimited": "刷新频率限制",
        "error.timeout": "请求超时",
        "error.noNetwork": "网络连接失败",
        "error.loadFailed": "加载失败",
        "error.noContent": "未返回内容",

        // Update
        "update.update": "更新",
        "update.check": "检查更新",
        "update.checkDev": "检查更新(dev)",
        "update.checking": "检查中",
        "update.upToDate": "已是最新 %@",
        "update.openInstaller": "打开安装包",
        "update.failedRetry": "更新失败，重新检查",
        "update.later": "稍后",
        "update.downloading": "更新中",
        "update.downloadingPercent": "更新 %ld%%",
        "update.failed": "更新失败",
        "error.aiGenerating": "AI 总结正在生成中",
        "error.aiTruncated": "AI 连续 %ld 次截断，请检查模型配置或减少新闻条目",
        "error.aiFormat": "AI 响应格式异常，未能解析出摘要板块",
        "error.aiKeyInvalid": "API Key 无效",
        "error.aiCapReached": "今日 AI 调用次数已达上限（%ld/%ld）",
        "error.aiUnavailable": "AI 服务暂时不可用（%@）",
        "error.aiBadFormat": "AI 响应格式异常",
        "error.aiFailed": "AI 总结生成失败",
        "error.aiTimeout": "AI 请求超时",
        "error.aiNoNetwork": "网络连接失败",
    ]

    // MARK: - English strings

    private static let enStrings: [String: String] = [
        // Units
        "unit.times": "times",
        "app.alert.noKeyTitle": "API Key Not Configured",
        "app.alert.noKeyBody": "The AI summary feature requires an API Key to work.\nWould you like to configure it in Settings?",
        "app.alert.goToSettings": "Go to Settings",
        "app.alert.later": "Later",
        "source.weibo": "Weibo Trending",
        "source.bilibili": "Bilibili Trending",
        "bottom.overview": "Overview",
        "bottom.openDashboard": "Open Dashboard",
        "bottom.openSettings": "Open Settings",
        "bottom.refresh": "Refresh",
        "bottom.refreshing": "Refreshing...",

        // General
        "settings.general": "General",
        "settings.general.subtitle": "Refresh, appearance & diagnostics",
        "settings.rss": "RSS Sources",
        "settings.rss.subtitle": "Subscribe, reorder & display",
        "settings.ai": "AI Editor",
        "settings.ai.subtitle": "Provider, model & usage",
        "settings.about": "About NewsBar",
        "settings.about.subtitle": "Version, sources & privacy",
        "settings.notifications": "Notifications",
        "settings.notifications.subtitle": "Permission, frequency & daily digest",
        "settings.tab.general": "General",
        "settings.tab.rss": "RSS",
        "settings.tab.ai": "AI",
        "settings.tab.notifications": "Notifications",
        "settings.tab.about": "About",
        "settings.tab.refresh": "Refresh",
        "settings.tab.reminder": "Reminders",
        "settings.tab.developer": "Developer",
        "settings.refresh": "Refresh & Diagnostics",
        "settings.refresh.subtitle": "Smart refresh, status & diagnostics",
        "settings.reminder": "Reminders",
        "settings.reminder.subtitle": "Scheduled push, burst & keyword tracking",
        "settings.developer": "Developer",
        "settings.developer.subtitle": "Testing, model expansion & debugging",
        "settings.developer.update": "Update Testing",
        "settings.developer.ai": "AI Debugging",
        "settings.badge": "Settings",
        "settings.quit": "Quit NewsBar",

        // Language
        "settings.language": "Language",
        "settings.language.footer": "Switch the interface language. When English is selected, you can enable RSS title translation and AI summaries will be generated in English.",
        "settings.rssTranslation": "RSS Title Translation",
        "settings.rssTranslation.footer": "When enabled, RSS titles are automatically translated to the selected language (free MyMemory translation service). Weibo and Bilibili trending stay in their original language.",

        // General - refresh
        "general.refresh": "Refresh",
        "general.autoRefresh": "Smart Auto Refresh",
        "general.autoRefresh.footer": "When enabled, trending is checked about every 5 minutes while visible and every 30 minutes in the background; RSS adapts between 30 minutes and 3 hours based on update activity. Frequency drops automatically on low battery and sleep.",
        "general.status": "Refresh Status",
        "general.todayRefreshCount": "Today's Refreshes",
        "general.todayAICount": "Today's AI Calls",
        "general.estimatedAICost": "Estimated AI Cost",
        "general.lastRefresh": "Last Refresh",
        "general.status.footer": "Includes startup, scheduled and manual refreshes; AI cost only estimates AI summary requests, not Weibo, Bilibili or RSS.",
        "general.launch": "Launch",
        "general.launchAtLogin": "Launch at Login",
        "general.theme": "Theme",
        "general.retroTheme": "Enable Retro Editorial Theme",
        "general.theme.paper": "Paper",
        "general.theme.brick": "Brick",
        "general.theme.ink": "Ink",
        "general.themeSwatchAccessibility": "Theme color (%@)",
        "general.appearance": "Appearance",
        "general.appearance.system": "System",
        "general.appearance.light": "Light",
        "general.appearance.dark": "Dark",
        "general.theme.footer.retro": "The retro editorial theme uses a fixed paper base; disable it to restore the modern theme and appearance options.",
        "general.theme.footer.modern": "The modern theme supports System, Light or Dark; the retro editorial theme uses 1960s editorial design language.",
        "general.diagnostics": "Diagnostics",
        "general.diagnostics.footer": "Records the last 10 refresh actions, diagnostic info only (no keys, passwords or sensitive data).",
        "general.refreshLog": "Refresh Log",
        "general.noLogs": "No refresh records",
        "general.copyLogs": "Copy last 10 logs",
        "general.copied": "Copied",
        "general.clearLogs": "Clear Logs",
        "general.developer": "Developer Options",
        "general.forceLatest": "Ignore version, force download latest",
        "general.showAllModels": "Show All AI Models",
        "general.developer.footer": "“Ignore version” is only for testing updates; when enabled, “Check Update” fetches the latest release directly.\n“Show All AI Models” stops folding the provider model list: providers with DeepSeek models also show their full official model list (e.g. Ollama Cloud, MiniMax, etc.). By default only DeepSeek-family models are shown.",
        "general.log.trigger.startup": "Startup",
        "general.log.trigger.timer1h": "Timer",
        "general.log.trigger.scheduled": "Smart",
        "general.log.trigger.wake": "Wake",
        "general.log.trigger.manual": "Manual",
        "general.log.trigger.popoverOpen": "Popover",
        "general.log.trigger.burst": "Burst Research",

        // AI
        "ai.enable": "Enable AI Summary",
        "ai.feature": "Feature",
        "ai.provider": "Provider",
        "ai.addCustomProvider": "Add Custom Provider",
        "ai.editProvider": "Edit",
        "ai.delete": "Delete",
        "ai.provider.footer.custom": "Currently using a custom provider; you can edit or delete it above.",
        "ai.apiKey": "API Key",
        "ai.save": "Save",
        "ai.saving": "Saving...",
        "ai.test": "Test Connection",
        "ai.testing": "Testing...",
        "ai.apiKey.footer": "API Key is encrypted with AES-256-GCM and bound to this machine. Get a Key: %@",
        "ai.1password": "1Password Integration",
        "ai.loadFrom1Password": "Load from 1Password",
        "ai.loading": "Loading...",
        "ai.1password.footer": "Format: op://Vault/Item/Field. Install the op CLI (brew install 1password-cli) and enable desktop integration to use it. Keys are cached for 30 days after loading.",
        "ai.model": "Model",
        "ai.modelSettings": "Model Settings",
        "ai.model.footer": "Folded to DeepSeek-family models by default; enable “Show All AI Models” under General → Developer Options to see all provider models.",
        "ai.disableThinking": "Disable DeepSeek thinking mode (faster output)",
        "ai.disableThinking.footer": "DeepSeek V4 enables thinking mode by default; the reasoning trace consumes output quota and adds latency. Disabling it speeds up summaries and avoids truncation, at a slight cost to complex-summary accuracy.",
        "ai.summaryLength": "Shared Summary Length",
        "ai.summaryLength.footer": "Popup and Dashboard share one generated result; Popup shows at most 2 rows per category, Dashboard shows the full briefing.",
        "ai.pricing": "Pricing",
        "ai.usage": "Usage",
        "ai.usage.today": "Used Today (Total)",
        "ai.usage.shared": "The same summary serves both Popup and Dashboard, not billed twice.",
        "ai.usage.reset": "Resets daily",
        "ai.limit": "Limit",
        "ai.dailyCap": "Daily Request Cap",
        "ai.capTimes": "%ld times",
        "ai.limit.footer": "Once the shared cap is reached, no more AI requests are made that day; it resets automatically the next day.",
        "ai.privacy": "Privacy",
        "ai.privacy.body": "The AI summary feature sends current news titles to your chosen AI provider for processing. We do not record your raw titles or prompts. API Keys are encrypted with AES-256-GCM and bound to this machine.",
        "ai.deleteCustom.title": "Delete custom provider?",
        "ai.deleteCustom.message": "This removes “%@” and its API Key from the list. This cannot be undone.",
        "ai.deleteCustom.confirm": "Delete %@",
        "ai.cancel": "Cancel",
        "ai.saved": "Saved",
        "ai.saveFailed": "Save failed, please retry",
        "ai.test.success": "Connection successful",
        "ai.test.empty": "Empty response",
        "ai.test.noKey": "Enter or save an API Key first",
        "ai.test.emptyKey": "API Key cannot be empty",
        "ai.test.invalidKey": "Invalid API Key (401)",
        "ai.test.requestFailed": "Request failed, check network or model name",
        "ai.test.invalidURL": "Internal error: invalid URL",
        "ai.test.parseFailed": "Response parse failed, model may be unavailable",
        "ai.test.parseFailedDetail": "Response parse failed: %@",
        "ai.test.unknown": "Unknown error",
        "ai.test.timeout": "Connection timed out (30s), check network or proxy",
        "ai.test.noNetwork": "No network connection",
        "ai.test.cannotFindHost": "Cannot resolve server: %@",
        "ai.test.networkLost": "Network connection lost",
        "ai.test.networkError": "Network error: %@",
        "ai.test.badResponse": "Server returned an unexpected format, check if the model is available",
        "ai.test.failed": "Connection failed: %@",
        "ai.1p.invalidRef": "Invalid format: must start with op://, format op://Vault/Item/Field",
        "ai.1p.notInstalled": "1Password CLI not installed, run: brew install 1password-cli",
        "ai.1p.timeout": "Timed out: unlock the 1Password desktop app first",
        "ai.1p.readFailed": "Read failed: check the reference format and permissions",
        "ai.1p.success": "Loaded and saved",
        "ai.1p.saveFailed": "Save failed, please retry",
        "ai.1p.unknown": "Unknown error",
        "ai.custom.title.add": "Add Custom Provider",
        "ai.custom.title.edit": "Edit Provider",
        "ai.custom.name": "Name",
        "ai.custom.endpoint": "Endpoint URL",
        "ai.custom.defaultModel": "Default Model",
        "ai.custom.models": "Model list (one model id per line)",
        "ai.custom.anthropic": "Anthropic-compatible format",
        "ai.custom.authHeaderName": "Auth header name (default x-api-key)",
        "ai.custom.authPrefix": "Auth prefix (default empty)",
        "ai.custom.apiVersion": "API version (default 2023-06-01)",
        "ai.custom.authHeaderNameOpenAI": "Auth header name (default Authorization)",
        "ai.custom.authPrefixOpenAI": "Auth prefix (default Bearer )",
        "ai.custom.pricing": "Pricing note (optional)",
        "ai.custom.needModel": "Enter at least one model",
        "ai.custom.invalidURL": "Invalid endpoint URL",
        "ai.custom.save": "Save",
        "ai.custom.cancel": "Cancel",

        // RSS
        "rss.displayCount": "Display Count",
        "rss.unifiedCount": "Unified Display Count",
        "rss.textFlow": "Text Flow",
        "rss.imageFlow": "Image Flow",
        "rss.displayCount.footer.unified": "When enabled, all RSS sources share the same text/image display counts.",
        "rss.displayCount.footer.perSource": "When disabled, set counts per source by display mode; right-click to reset to the global default.",
        "rss.subscribed": "Subscribed RSS Sources",
        "rss.hideRecommendations": "Hide Recommendations",
        "rss.showRecommendations": "Recommendations",
        "rss.subscribed.footer": "Drag subscribed sources to reorder; text/image flow settings are preserved.",
        "rss.unsubscribed": "Unsubscribed RSS Sources",
        "rss.recommendationValidation": "Recommendation Validation",
        "rss.recommendationValidation.footer": "Only tests unadded recommendations; testing does not modify subscriptions, order or notifications.",
        "rss.addSource": "Add RSS Source",
        "rss.empty": "No RSS sources yet. Add from the recommendations below or manually.",
        "rss.emptySubscribed": "No subscribed RSS sources yet. Check items in the unsubscribed list.",
        "rss.delete.title": "Delete RSS source?",
        "rss.delete.message": "This removes “%@” from the subscribed and unsubscribed lists. Local cache files are not deleted, but you must re-add it to restore.",
        "rss.delete.confirm": "Delete %@",
        "rss.delete.cancel": "Cancel",
        "rss.textMode": "Text Flow",
        "rss.imageMode": "Image Flow",
        "rss.switchToText": "Switch %@ to text flow",
        "rss.switchToImage": "Switch %@ to image flow",
        "rss.imageUnavailable": "%@ image flow unavailable",
        "rss.noImages": "This source has no images",
        "rss.moveUp": "Move %@ up",
        "rss.moveDown": "Move %@ down",
        "rss.up": "Up",
        "rss.down": "Down",
        "rss.subscribe": "Subscribe %@",
        "rss.unsubscribe": "Unsubscribe %@",
        "rss.subscribe.short": "Subscribe",
        "rss.unsubscribe.short": "Unsubscribe",
        "rss.resetToGlobal": "Reset to Global Default",
        "rss.countAccessibility": "%@ %@ display count",
        "rss.countHint": "Hold or right-click to reset to the global default display count.",
        "rss.resetCount": "Reset %@ display count",
        "rss.delete": "Delete %@",
        "rss.delete.short": "Delete",
        "rss.deleteHint": "Requires confirmation before removing this RSS source.",
        "rss.dragReorder": "Drag to reorder %@",
        "rss.dragReorderShort": "Drag to reorder",
        "rss.dragHint": "Hold and drag to reorder subscribed RSS sources",
        "rss.add": "Add",
        "rss.addNamed": "Add %@",
        "rss.addHint": "Validated against security policies before adding.",
        "rss.alreadyExists": "This recommendation already exists, no need to add again",
        "rss.blocked": "Recommendation blocked: %@",
        "rss.warning": "Recommendation has a security warning: %@",
        "rss.testAll": "Test All Unadded",
        "rss.retryFailed": "Retry Failed/Cancelled",
        "rss.continueTesting": "Continue Unfinished",
        "rss.testHint.retry": "Only re-validates failed, cancelled or unfinished recommendations; successful ones stay unchanged.",
        "rss.testHint.continue": "Continues validating unfinished recommendations; already-passed items are not retested.",
        "rss.testHint.all": "Validates all unadded recommendations in order; testing does not change the subscription list.",
        "rss.cancel": "Cancel",
        "rss.cancelValidation": "Cancel Validation",
        "rss.cancelValidationHint": "Stops recommendations that have not started; the current source ends at a cancellable point.",
        "rss.progress": "Progress %ld/%ld",
        "rss.current": "Current: %@",
        "rss.waitingNext": "Waiting for next",
        "rss.testing": "Testing",
        "rss.noTestable": "No testable recommendations",
        "rss.testOnlyUnadded": "Only tests unadded recommendations",
        "rss.added": "Added",
        "rss.addedHint": "Recommendation added to the subscription list.",
        "rss.testingBadge": "Testing",
        "rss.testingBadgeHint": "Currently validating this recommendation.",
        "rss.pending": "Pending",
        "rss.pendingHint": "Not yet validated.",
        "rss.blockedBadge": "Blocked",
        "rss.blockedBadgeHint": "Blocked by security policy: %@",
        "rss.invalidURL": "Invalid URL",
        "rss.invalidURLHint": "The address format is invalid.",
        "rss.cancelled": "Cancelled",
        "rss.cancelledHint": "Validation stopped; later recommendations did not continue.",
        "rss.cancelledWithBody": "Cancelled: %@; %ld items stopped",
        "rss.networkFailed": "Network Failed",
        "rss.networkFailedHint": "%@",
        "rss.notRSS": "Not RSS",
        "rss.notRSSHint": "The response is not RSS or Atom.",
        "rss.passed": "Passed",
        "rss.passedHint": "Validated, about %ld items.",
        "rss.noRetryable": "No retryable recommendations",
        "rss.retrying": "Retrying %ld items",
        "rss.testingCount": "Testing %ld items",
        "rss.cancelledStop": "Cancelled, later recommendations stopped",
        "rss.testingProgress": "Testing %ld/%ld",
        "rss.retryDone": "Retry complete",
        "rss.testDone": "Testing complete",
        "rss.noResult": "No results",
        "rss.cancelledResult": "Cancelled: %ld items stopped",
        "rss.passedCount": "%ld passed",
        "rss.failedCount": "%ld failed",
        "rss.sourceName": "Source Name",
        "rss.url": "RSS URL",
        "rss.addAndValidate": "Add & Validate",
        "rss.waterfall.imageMode": "Image",
        "rss.waterfall.textMode": "Text",
        "rss.waterfall.imagePlaceholder": "RSS Image",
        "rss.readOriginal": "Read Original",
        "rss.waterfall.accessibility": "%@, %@",
        "rss.waterfall.accessibilityDash": "%@ - %@",
        "rss.needURL": "Enter an RSS URL",
        "rss.notValidFeed": "This address is not a valid RSS/Atom feed",
        "rss.cannotConnect": "Cannot connect to this address",
        "rss.security.invalidURL": "Invalid URL or scheme",
        "rss.security.blockedHost": "Blocked host: %@",
        "rss.security.privateIP": "Private IP range: %@",
        "rss.network.timedOut": "Request timed out",
        "rss.network.cannotConnect": "Cannot connect to server",
        "rss.network.noInternet": "No internet connection",
        "rss.network.serverNotFound": "Server not found",
        "rss.network.invalidResponse": "Invalid server response",
        "rss.network.serverError": "Server returned an error",
        "rss.network.parseFailed": "Feed parse failed",
        "rss.network.unexpected": "Unexpected error",
        "rss.network.generic": "Network error",

        // Notifications
        "notif.hourly": "Hourly Push",
        "notif.daily": "Daily Push",
        "notif.pushCount": "Push Count",
        "notif.dailyTime": "Daily Push Time",
        "notif.permission": "Notification Permission",
        "notif.permission.granted": "Granted",
        "notif.permission.denied": "Denied",
        "notif.permission.notDetermined": "Not Requested",
        "notif.requestPermission": "Request Permission",
        "notif.openSettings": "Open System Settings",
        "notif.hourlyTitle": "NewsBar Updated",
        "notif.dailyTitle": "NewsBar Daily Digest",
        "notif.clickToView": "Click to view today's news",
        "notif.grantedTitle": "Notification permission enabled",
        "notif.notGrantedTitle": "Notification permission disabled",
        "notif.openSystemSettings": "Open System Settings",
        "notif.permissionStatus": "Permission Status",
        "notif.hourlyPushNews": "Push latest news hourly",
        "notif.scheduled": "Scheduled Push",
        "notif.dailyDigest": "Daily digest push",
        "notif.pushTime": "Push Time",
        "notif.dailyPush": "Daily Push",
        "notif.pushCountLabel": "Items per push: %ld",
        "notif.pushQuantity": "Push Quantity",
        "notif.pushCount.footer": "The hourly push sends the latest content after each auto refresh; the daily push sends at the specified time with the most recent refresh result.",
        "notif.burstPush": "Burst Realtime Push",
        "notif.burst": "Burst Push",
        "notif.burst.footer": "When a Weibo “爆” label appears, push a single notification and run AI research (context & timeline).",
        "notif.webSearch": "Web Search Research",
        "notif.webSearchHeader": "Web Search",
        "notif.webSearch.footer": "When enabled, burst research uses Firecrawl web search (keyless free tier); otherwise it degrades to pure-AI generation. Leave the API key blank to use the free quota.",
        "notif.firecrawlKey": "Firecrawl API Key (optional)",
        "notif.keywordTracking": "Keyword Tracking",
        "notif.keywordTracking.footer": "Scans Weibo, Bilibili trending and enabled RSS titles; a match on any keyword pushes a single notification and runs AI research (context & timeline).",
        "notif.keywordPrompt": "Keywords to track",
        "notif.keywordAdd": "Add Keyword",
        "notif.keywordEmpty": "No keywords yet. Type one and press Enter to add.",
        "notif.keywordRemove": "Remove %@",
        "notif.keywordTitle": "Keyword Matched",

        // Burst (爆) topic
        "notif.burstTitle": "Weibo Burst",
        "burst.badge": "Burst Hot News",
        "burst.subtitle": "AI research · context & timeline",
        "burst.loading": "AI is researching this event...",
        "burst.failed": "Research failed. Please retry.",
        "burst.retry": "Research Again",
        "burst.summary": "Quick Summary",
        "burst.summary.subtitle": "The event in one glance",
        "burst.overview": "Context",
        "burst.overview.subtitle": "The full chain of events",
        "burst.timeline": "Timeline",
        "burst.timeline.subtitle": "Key moments in chronological order",
        "burst.sources": "Sources",
        "burst.sources.subtitle": "References used in this research",
        "burst.noTimeline": "Not enough material to build a timeline; showing summary only.",
        "burst.noSummary": "No summary available",
        "burst.searchFailed": "Web search failed; degraded to pure-AI generation (see refresh log).",
        "burst.testMode": "Burst Push Test Mode",
        "burst.testMode.footer": "“Web Search Research” controls whether the simulated push runs Firecrawl web search (independent of the realtime search toggle in Notifications). The simulated push opens the detail window first, then researches in the background.",
        "burst.testWebSearch": "Web Search Research",
        "burst.testPush": "Simulate Burst Push",
        "burst.testTopic.placeholder": "Enter a hot-search title to test",
        "burst.testTopic.fillTop": "Use current #1 trend",

        // About
        "about.version": "Version",
        "about.license": "License",
        "about.source": "Data Sources",
        "about.privacy": "Privacy",
        "about.checkUpdate": "Check Update",
        "about.versionText": "Version %@ (%@)",
        "about.weibo": "Weibo Trending",
        "about.bilibili": "Bilibili Trending",
        "about.rss": "RSS Sources",
        "about.rssCustom": "User-defined",
        "about.dataSources": "Data Sources",
        "about.aiModels": "Supports multiple AI APIs, freely choose your model",
        "about.aiProviders": "AI Providers",
        "about.clearCache": "Clear All Cache",
        "about.dataManagement": "Data Management",
        "about.privacy1": "NewsBar does not collect any personal information.",
        "about.privacy2": "API Keys are stored only in machine-bound encrypted files locally.",
        "about.privacy3": "Cache stores only news titles, no user data.",
        "about.privacy4": "All network requests are transmitted over HTTPS.",
        "about.privacyTitle": "Privacy",
        "about.keywords": "Keywords: macOS menu bar · news aggregator · AI summaries · Weibo trending · Bilibili trending · RSS reader",
        "about.licenseTitle": "License & Info",
        "about.clearCache.title": "Clear all cache?",
        "about.cancel": "Cancel",
        "about.clearCache.message": "This clears the local news cache. Content will need to be reloaded on next open or refresh.",

        // Popover
        "popover.trending": "Trending Now",
        "popover.trending.subtitle": "What's happening on Weibo & Bilibili",
        "popover.weibo": "Weibo Trending",
        "popover.bilibili": "Bilibili Trending",
        "popover.rss.subtitle": "Subscriptions · Editor's Picks",
        "popover.collapse": "%@ · Collapse",
        "popover.allFailed": "All news sources failed to update, please try again later",
        "popover.quit.title": "Quit NewsBar?",
        "popover.quit.message": "NewsBar will stop refreshing news and sending notifications.",
        "popover.quit.confirm": "Quit NewsBar",
        "popover.quit.cancel": "Cancel",
        "popover.quit.help": "Quit NewsBar",
        "popover.issueDate": "SHANGHAI EDITION",
        "popover.issueNumber": "NO. %@",

        // News section
        "news.clickToOpen": "Click to open in browser",
        "news.loading": "Loading",
        "news.loadingDots": "Loading...",
        "news.loadFailed": "Load Failed",
        "news.noData": "No data",
        "news.staleCache": "Update failed, showing cache",
        "news.expand": "Expand %ld items",
        "news.collapse": "Collapse",
        "news.collapseCount": "Collapse %ld items",
        "news.count": "%ld items",
        "news.openInBrowser": "Open in browser",
        "news.rank": "Rank %ld, %@, %@",
        "news.rankBadge": "Rank %ld",
        "news.rankAccessibility": "Rank %ld, %@, %@",

        // AI summary card
        "aiCard.title": "AI Summary",
        "aiCard.subtitle": "Trend Overview / Daily Essentials · citations show a source badge, click to open",
        "aiCard.expandHint": "Expand AI summary",
        "aiCard.collapseHint": "Collapse AI summary",
        "aiCard.noKey": "Not Configured",
        "aiCard.fetching": "Fetching",
        "aiCard.summarizing": "Thinking",
        "aiCard.failed": "Failed",
        "aiCard.done": "Done",
        "aiCard.truncated": "Incomplete",
        "aiCard.idle": "Waiting",
        "aiCard.noKeyTitle": "API Key Not Configured",
        "aiCard.noKeyBody": "Configure an AI API Key to use the AI summary feature",
        "aiCard.configureKey": "Configure Key",
        "aiCard.fetchingData": "Fetching news data...",
        "aiCard.thinking": "AI thinking...",
        "aiCard.maybeIncomplete": "Summary may be incomplete",
        "aiCard.trendOverview": "Trend Overview",
        "aiCard.dailyEssentials": "Daily Essentials",
        "aiCard.regenerating": "Generating...",
        "aiCard.cooldown": "Cooldown %lds",
        "aiCard.regenerate": "Regenerate",
        "aiCard.regenerateHint": "Regenerate the AI summary shared by Popup and Dashboard.",
        "aiCard.cooldownHint": "Wait for the cooldown to finish before regenerating.",
        "aiCard.openSource": "Open %@ original",
        "aiCard.openInBrowser": "Open in browser",
        "aiCard.readonly": "This is read-only summary content.",
        "aiCard.sourceHint": "Use the source button to open the original.",
        "aiCard.noSource": "No source available",

        // Dashboard
        "dash.briefing": "AI Briefing",
        "dash.briefing.subtitle": "Trend Overview / Daily Essentials · citations show a source badge, click to open",
        "dash.refresh": "Refresh AI Briefing",
        "dash.trendOverview": "Trend Overview %ld",
        "dash.dailyEssentials": "Daily Essentials %ld",
        "dash.trendCardSubtitle": "Native hot-trend card · click to open in browser",
        "dash.collapseCard": "Collapse %@",
        "dash.expandCard": "Expand more %@",
        "dash.expandAll": "Expand All",
        "dash.noTrendData": "No trending data",
        "dash.waterfallSubtitle": "Adaptive waterfall · click to open in browser",
        "dash.noRSSContent": "No RSS content",
        "dash.rssLoading": "RSS source loading…",
        "dash.rssLoadingCache": "RSS source loading, showing cached content",
        "dash.trendRankAccessibility": "%@ Rank %ld, %@",
        "dash.source.idle": "Idle",
        "dash.source.loading": "Loading",
        "dash.source.loaded": "Loaded",
        "dash.source.failed": "Failed",
        "dash.rssBatchRefreshing": "Refreshing RSS in batch",
        "dash.legacyNote": "This summary uses compatible parsing: the citation snapshot is preserved and you can still switch between the two categories.",
        "dash.fallbackNote": "No citation snapshot is available; source links will be restored after the next refresh.",
        "dash.fallbackTitle": "Summary content is available but not yet parsed into the two-category structure.",
        "dash.emptyCategory": "No content in this category",
        "dash.noBriefing": "No AI briefing to display",
        "dash.openSettings": "Open Settings",
        "dash.state.idle": "Waiting for AI briefing",
        "dash.state.noKey": "API Key not configured",
        "dash.state.fetching": "Fetching news",
        "dash.state.summarizing": "AI is generating the briefing",
        "dash.state.done": "AI briefing complete",
        "dash.state.truncated": "AI briefing complete but truncated",
        "dash.state.error": "AI briefing generation failed",
        "dash.compatFormat": "Compatible Format",
        "dash.configureKey": "Configure AI Key",
        "dash.searchPlaceholder": "Search Weibo, Bilibili trending & RSS titles…",
        "dash.searchClear": "Clear search",
        "dash.filter.all": "All",
        "dash.filter.rss": "RSS",
        "dash.filterCount": "%ld matches",

        // Errors
        "error.invalidURL": "Invalid URL",
        "error.requestFailed": "Network request failed",
        "error.parseFailed": "Data parse failed",
        "error.parseFailedDetail": "XML parse failed: %@",
        "error.apiKeyInvalid": "Invalid API Key",
        "error.rateLimited": "Refresh rate limit",
        "error.timeout": "Request timed out",
        "error.noNetwork": "Network connection failed",
        "error.loadFailed": "Load failed",
        "error.noContent": "No content returned",

        // Update
        "update.update": "Update",
        "update.check": "Check Update",
        "update.checkDev": "Check Update (dev)",
        "update.checking": "Checking",
        "update.upToDate": "Up to date %@",
        "update.openInstaller": "Open Installer",
        "update.failedRetry": "Update failed, check again",
        "update.later": "Later",
        "update.downloading": "Updating",
        "update.downloadingPercent": "Updating %ld%%",
        "update.failed": "Update failed",
        "error.aiGenerating": "AI summary is being generated",
        "error.aiTruncated": "AI truncated %ld times in a row, check the model config or reduce news items",
        "error.aiFormat": "AI response format error, could not parse summary sections",
        "error.aiKeyInvalid": "Invalid API Key",
        "error.aiCapReached": "Daily AI call limit reached (%ld/%ld)",
        "error.aiUnavailable": "AI service temporarily unavailable (%@)",
        "error.aiBadFormat": "AI response format error",
        "error.aiFailed": "AI summary generation failed",
        "error.aiTimeout": "AI request timed out",
        "error.aiNoNetwork": "Network connection failed",
    ]
}

extension String {
    var localized: String {
        L10n.string(self)
    }
}
